### ISSUE TITLE
only ever one marathon event subscriber?

### ISSUE THREAD

**Issue by jeacott** [tobilg/docker-mongodb-marathon#1]
hi,
 looking at this code,

```
     if (isInitialRun) {
          marathon.setupEventCallback(options.host, options.webPort.public)
         ...
         mongoDb.initializeReplicaSet()
                      .then(function(result) {
                        // Now we are ready to handle the events from Marathon
                        isReady = true;
```

unless I missed something, only the first instance that registers a node with zk can create a marathon event listener, and is also the only instance that isReady is ever == true.

if my first instance (in a replicaset) dies, and a new mongo master is elected, how can it's instance ever subscribe or react? (because even if it subscriibes, its isReady will always be false).

what am I missing?

**Comment by tobilg** [comment]
You're correct, and this was initially intended as-is. This project is not yet production-ready, because auth features are not yet implemented. Please keep that in mind.

I added a [new functionality](https://github.com/tobilg/docker-mongodb-marathon/blob/master/mongodb-configurator/routes/all.js#L228-L263) so that all node start to listen to Marathon events once the cluster was initialized. The secondary node will safely ignore the updates, until the master crashes and a secondary is elected a the new master.

**Comment by tobilg** [comment]
The images have been built on the [Docker Hub](https://hub.docker.com/r/tobilg/mongodb-marathon/tags/). Please check and close the issue if it's resolved.

**Comment by jeacott1** [comment]
I think a better solution is to just subscribe every instance to marathon,
 and set ready=true unless its the initial node. Thats what I've done anyway. seems to work fine.

**Comment by tobilg** [comment]
Why would this be a better solution? I think it's correct to wait until the cluster setup is finished. 

Anyway, I'll keep it the way it is now.
